=== AbyssAbbeba/MDS-picoblaze-AVR-ide/IDE/utilities/LicenseCertificate/LicenseCertificate-1.1.dtd
<!--
  -- XML DTD for license certificates v1.1 issued by Moravia Microsystems, s.r.o.
  --
  -- (C) copyright 2014 Moravia Microsystems, s.r.o.
  --
  -- http://www.moravia-microsystems.com
  -->

<!-- Data types used here. -->
<!ENTITY % Integer "CDATA">
<!ENTITY % String  "CDATA">

<!-- Root element. -->
<!ELEMENT certificate (product, licensee, system)>
<!ATTLIST certificate
    <!-- Version of license certificate format. -->
    version %String; #REQUIRED
>
<!-- Information of the licensed product and type of license. -->
<!ELEMENT product (designation, licences, variant, grade, target)>
<!-- Name of product covered by the license. -->
<!ELEMENT designation (#PCDATA)>
<!-- Number of licenses issued. -->
<!ELEMENT licences (#PCDATA)>
<!-- Product variant, one of {Commercial,Noncommercial}. -->
<!ELEMENT variant (#PCDATA)>
<!-- Product grade, one of {Basic,Premium,Professional,Ultimate}. -->
<!ELEMENT grade (#PCDATA)>
<!-- Processor architecture or similar. -->
<!ELEMENT target (#PCDATA)>
<!-- Information about to whom the license was or has been granted. -->
<!ELEMENT licensee (name, type, email, phone, address)>
<!-- Subject name. -->
<!ELEMENT name (#PCDATA)>
<!-- Type of subject, one of: {company,school,individual,other}. -->
<!ELEMENT type (#PCDATA)>
<!-- Email address associated with the registered customer. -->
<!ELEMENT email (#PCDATA)>
<!-- Contact phone (optional). -->
<!ELEMENT phone (#PCDATA)>
<!-- Address of the licensee. -->
<!ELEMENT address (country, state, municipality, street, number, post)>
<!-- Sovereign state (e.g. United States of America, Federal Republic of Germany, Russian Federation). -->
<!ELEMENT country (#PCDATA)>
<!-- Dependent state (optional) (e.g. Republic of Texas, Freistaat Bayern, Novosibirsk Oblast). -->
<!ELEMENT state (#PCDATA)>
<!-- City/town or other type of municipality (e.g. Dallas, MÃ¼nchen, Novosibirsk). -->
<!ELEMENT municipality (#PCDATA)>
<!-- Street name. -->
<!ELEMENT street (#PCDATA)>
<!-- House number or similar designation. -->
<!ELEMENT number (#PCDATA)>
<!-- Postal code. -->
<!ELEMENT post (#PCDATA)>
<!-- Software details related to certificate file generation. -->
<!ELEMENT system (timestamp, userid, orderid)>
<!-- Unix time stamp (seconds since 1970-01-01 00:00:00 UTC) - time of generation. -->
<!ELEMENT timestamp (#PCDATA)>
<!-- Some Unique User ID from web page DB table(s) hashed with MD5 as hexadecimal string. -->
<!ELEMENT userid (#PCDATA)>
<!-- Some Unique Order ID from web page DB table(s) hashed with MD5 as hexadecimal string. -->
<!ELEMENT orderid (#PCDATA)>

=== AbyssAbbeba/MDS-picoblaze-AVR-ide/IDE/utilities/LicenseCertificate/CertificateExample.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE certificate
    PUBLIC "-//Moravia Microsystems//License Certificate File 1.0//EN"
    "http://www.moravia-microsystems.com/LicenseCertificate-1.1.dtd">

<certificate version="1.1">
    <product>
        <designation>Multitarget Development System</designation>
        <licences>5</licences>
        <variant>Commercial</variant>
        <grade>Professional</grade>
        <target>PicoBlaze</target>
    </product>
    <licensee>
        <name>Kelio s.r.o.</name>
        <type>company</type>
        <email>info@kelio.cz</email>
        <phone>+420777776720</phone>
        <address>
            <country>Czech Republic</country>
            <state></state>
            <municipality>Brno</municipality>
            <street>Maniƒçky</street>
            <number>43/12</number>
            <post>61600</post>
        </address>
    </licensee>
    <system>
        <timestamp>1406890984</timestamp>
        <userid>454503058c5b68f4d2e2dd3fb390b93a</userid>
        <orderid>2f498969904778335f1c320479ebefbc</orderid>
    </system>
</certificate>
